name: horologyb
favicon: null
layout_spectrum: 0.83389
typography_spectrum: 0.5505698141641915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.19473248650319874
  lightness: 0.38823178224265575
  saturation: 0.5013370348606259
  rhythmicContrast: 0.2265082544181496
purpose: []
